server:
  port: 8073
spring:
  application.name: eureka-client
eureka:
  client:
    prefer-same-zone-eureka: true
    region: region-guangzhou
    service-url:
      zone3: http://localhost:8763/eureka/
      zone4: http://localhost:8764/eureka/
    availability-zones:
      region-guangzhou: zone3,zone4
  instance:
    metadataMap.zone: zone3
