server:
  port: 8072
spring:
  application.name: eureka-client
eureka:
  client:
    prefer-same-zone-eureka: true
    region: region-beijing
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://localhost:8762/eureka/
    availability-zones:
      region-beijing: zone1,zone2
  instance:
    metadataMap.zone: zone2
