server:
  port: 8081

spring:
  application:
    name: eureka-client1

eureka:
  client:
    securePortEnabled: true
    ssl:
      key-store: eureka.client
      key-store-password: client
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/